spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/MAIL_AUTOMATION
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: slack-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          json:
            trusted-packages: "*"
    template:
      default-topic: gmail-topic

logging:
  level:
    root: INFO
    com.example: DEBUG